#docker-compose.yml
version: '3'

services:
  api:
    # working_dir: /app
    build: 
      context: .
      dockerfile: app.dockerfile
    volumes:
      - ./app:/app
      - ./conf.d/uwsgi.ini:/uwsgi/uwsgi.ini
    env_file:
      - ./payment.env
  nginx:
    image: nginx
    volumes:
      - ./conf.d/nginx.conf:/etc/nginx/conf.d/nginx.conf
      - ./app:/app
    ports:
      - "${PORT}:8000"
    links:
      - api
