# Generated by Django 2.2 on 2019-05-15 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_guesttemporaryinfo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'managed': True},
        ),
    ]
