# Generated by Django 2.2 on 2019-05-15 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_auto_20190515_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='id',
            field=models.CharField(db_column='pk', default='a306e4ab-57ca-437e-9a38-a9ed94', max_length=40, primary_key=True, serialize=False, unique=True),
        ),
    ]
