# Generated by Django 2.2 on 2019-05-15 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_auto_20190515_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='ecpay_merchant_trade_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='id',
            field=models.CharField(db_column='pk', default='9cb8915b-839c-49a4-a6e0-bf5e95', max_length=40, primary_key=True, serialize=False, unique=True),
        ),
    ]
