# Generated by Django 2.2 on 2019-05-27 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_auto_20190515_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='guesttemporaryinfo',
            name='guest_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='guesttemporaryinfo',
            name='id',
            field=models.CharField(default='940f2474-4d46-4fe2-8de3-c4833d', max_length=255, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='id',
            field=models.CharField(db_column='pk', default='5c07b980-6574-4c75-99fe-d00cc4', max_length=30, primary_key=True, serialize=False, unique=True),
        ),
    ]
