# Generated by Django 2.2 on 2019-05-27 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_auto_20190527_0550'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='newebpay_merchant_trade_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='guesttemporaryinfo',
            name='id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='id',
            field=models.CharField(db_column='pk', default='ffe85f8c-8980-4713-aeb1-765530', max_length=30, primary_key=True, serialize=False, unique=True),
        ),
    ]
