# Generated by Django 2.2 on 2019-05-27 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_auto_20190527_0741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guesttemporaryinfo',
            name='id',
            field=models.CharField(default='f5fdaa44', max_length=255, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='id',
            field=models.CharField(db_column='pk', default='739c64d7-e23d-41a8-8433-ed3adb', max_length=30, primary_key=True, serialize=False, unique=True),
        ),
    ]
