# Generated by Django 2.2 on 2019-05-27 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_auto_20190527_0751'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GuestTemporaryInfo',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='id',
            field=models.CharField(db_column='pk', default='0d1910c0-67a3-4bae-ad45-afdd38', max_length=30, primary_key=True, serialize=False, unique=True),
        ),
    ]
