# Generated by Django 2.2 on 2019-05-27 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0009_auto_20190527_0805'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestTemporaryInfo',
            fields=[
                ('id', models.CharField(default='0e251484', max_length=255, primary_key=True, serialize=False, unique=True)),
                ('email', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('mobile', models.CharField(max_length=255)),
                ('learners', models.CharField(max_length=255)),
                ('schedule_id', models.CharField(max_length=255)),
                ('auto_create_account', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('guest_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'guest_temp_infos',
                'managed': True,
            },
        ),
        migrations.AlterField(
            model_name='transaction',
            name='id',
            field=models.CharField(db_column='pk', default='eac68d2b-9db4-434f-8c97-d97698', max_length=30, primary_key=True, serialize=False, unique=True),
        ),
    ]
