# Generated by Django 2.2 on 2019-05-30 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0010_auto_20190527_0807'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionCounterPay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_id', models.CharField(max_length=255)),
                ('price_prefix', models.CharField(max_length=255)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('device_type', models.IntegerField(default=0)),
                ('booking_class_id', models.CharField(max_length=255)),
                ('booking_schedule_id', models.CharField(max_length=255)),
                ('vendor_id', models.CharField(max_length=255)),
                ('vendor_branch_id', models.CharField(max_length=255)),
                ('class_name', models.CharField(max_length=255)),
                ('option_name', models.CharField(max_length=255)),
                ('schedule_name', models.CharField(max_length=255)),
                ('vendor_name', models.CharField(max_length=255)),
                ('branch_name', models.CharField(max_length=255)),
                ('learner_count', models.IntegerField()),
                ('class_date', models.CharField(blank=True, max_length=255, null=True)),
                ('class_time', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('learners', models.CharField(max_length=255)),
                ('date_added', models.DateTimeField()),
            ],
            options={
                'db_table': 'transaction_counterpay',
                'managed': True,
            },
        ),
        migrations.AlterField(
            model_name='guesttemporaryinfo',
            name='id',
            field=models.CharField(default='5ba39202', max_length=255, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='id',
            field=models.CharField(db_column='pk', default='0903a0af-4b1b-487e-b77b-4708ac', max_length=30, primary_key=True, serialize=False, unique=True),
        ),
    ]
