# Generated by Django 2.2 on 2019-05-30 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0013_auto_20190530_0721'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TransactionCounterPay',
        ),
        migrations.AlterField(
            model_name='guesttemporaryinfo',
            name='id',
            field=models.CharField(default='092f3266', max_length=255, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='id',
            field=models.CharField(db_column='pk', default='3c0a444f-793c-4a39-bbe0-8edcbb', max_length=30, primary_key=True, serialize=False, unique=True),
        ),
    ]
