# Generated by Django 2.2 on 2019-05-30 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0014_auto_20190530_0722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guesttemporaryinfo',
            name='id',
            field=models.CharField(default='c44f4edc', max_length=255, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='id',
            field=models.CharField(db_column='pk', default='a9615f4e-d591-47d4-841f-9361ce', max_length=30, primary_key=True, serialize=False, unique=True),
        ),
    ]
