# Generated by Django 2.2 on 2019-05-30 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0016_auto_20190530_0725'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TransactionCounterPay',
        ),
        migrations.AlterField(
            model_name='guesttemporaryinfo',
            name='id',
            field=models.CharField(default='04a3cd55', max_length=255, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='id',
            field=models.CharField(db_column='pk', default='bbfdbe6d-0da3-4904-bfcc-3a5a1c', max_length=30, primary_key=True, serialize=False, unique=True),
        ),
    ]
