# Generated by Django 2.2 on 2019-05-30 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0019_auto_20190530_0740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guesttemporaryinfo',
            name='id',
            field=models.CharField(default='a04d8752', max_length=255, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='id',
            field=models.CharField(db_column='pk', default='6f5165b4-1c8c-4fc7-954a-1d4e97', max_length=30, primary_key=True, serialize=False, unique=True),
        ),
    ]
