# Generated by Django 2.2 on 2019-05-30 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0020_auto_20190530_0741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guesttemporaryinfo',
            name='id',
            field=models.CharField(default='189f464b', max_length=255, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='id',
            field=models.CharField(db_column='pk', default='c3b5da53-a762-4dce-9747-8ceac1', max_length=30, primary_key=True, serialize=False, unique=True),
        ),
    ]
